#!/bin/bash
set -e

opt_label="rootdisk"
opt_subvol="volumes"
opt_prefix=""

volumes_prefix="${opt_prefix}/mnt/volumes"
snapshot_prefix="${volumes_prefix}/snapshots"

err() {
    echo "$@" >&2
}
die() {
    err "$@"
    exit 1
}

do_init() {
    volumes_prefix="${opt_prefix}/mnt/volumes"
    snapshot_prefix="${volumes_prefix}/snapshots"

    mkdir -p "${volumes_prefix}"
    mount -L "${opt_label}" -o rw,relatime,ssd,space_cache=v2,subvol="${opt_subvol}" "${volumes_prefix}"
}
do_uninit() {
    umount "${volumes_prefix}"
}


list() {
    ls -lha "${snapshot_prefix}"
}

# checkout [tag]
checkout() {
    local head branch tag
    head=$(readlink "${snapshot_prefix}/current")
    branch=${head%.*}

    tag="$1"
    [[ -z ${tag} ]] && tag="${branch}.$(date +%Y%m%d%H%M%S)"

    if [[ ! -e "${snapshot_prefix}/${tag}" ]]; then
        btrfs subvol snapshot "${snapshot_prefix}/${head}" "${snapshot_prefix}/${tag}"
    fi

    rm "${snapshot_prefix}/current"
    ln -sfT "${tag}" "${snapshot_prefix}/current"
}

delete() {
    local tag
    for tag in "$@"; do
        if [[ -e "${snapshot_prefix}/${tag}" ]]; then
            btrfs subvol delete "${snapshot_prefix}/${tag}" || err "delete volume ${tag} failed, please check ${snapshot_prefix}/${tag}"
        fi
    done
}

# exec <tag> <cmd>
exec() {
    local tag="$1"
    shift
    (cd "${snapshot_prefix}/${tag}" && eval "$*")
}

main() {
    if [[ $UID != '0' ]]; then
        die "can not manager rootfs as ${USER}"
    fi
    while (( $# )); do
        case $1 in
            -L | --label)
                opt_label="$2"
                shift 2
                ;;
            -p | --prefix)
                opt_prefix="$2"
                shift 2
                ;;
            --subvol)
                opt_subvol="$2"
                shift 2
                ;;
            *)
                break
                ;;
        esac
    done
    do_init
    trap "do_uninit" EXIT
    local action="$1"
    shift
    $action "$@"
}

main "$@"

