#!/bin/bash
set -e

# defer script
__func_defered=()
defer() {
    __func_defered+=("$*")
}
do_defer() {
    for ((i=${#__func_defered[@]}-1;i>=0;i--)); do
        if ! eval "${__func_defered[i]}"; then
            echo "eval cmd failed, cmd: \"${__func_defered[i]}\"" >&2
        fi
    done
}
trap do_defer EXIT
# defer script end

opt_label="rootdisk"
opt_subvol="volumes"
opt_prefix=""

volumes_prefix="${opt_prefix}/mnt/volumes"
snapshot_prefix="${volumes_prefix}/snapshots"

err() {
    echo "$@" >&2
}
die() {
    echo "$@" >&2
    exit 1
}

do_init() {
    volumes_prefix="${opt_prefix}/mnt/volumes"
    snapshot_prefix="${volumes_prefix}/snapshots"

    mkdir -p "${volumes_prefix}"
    mount -L "${opt_label}" -o rw,relatime,ssd,space_cache=v2,subvol="${opt_subvol}" "${volumes_prefix}"
}
do_uninit() {
    umount "${volumes_prefix}"
}


do_list() {
    ls -lha "${snapshot_prefix}"
}

# checkout [tag]
do_checkout() {
    local current="$(readlink "${snapshot_prefix}/current")"
    local tag="$1"
    if [[ -z "${tag}" ]]; then
        tag="${current%%.*}.$(date +%Y%m%d%H%M%S)"
    fi

    if [[ ! -e "${snapshot_prefix}/${tag}" ]]; then
        btrfs subvol snapshot "${snapshot_prefix}/${current}" "${snapshot_prefix}/${tag}"
    fi
    rm "${snapshot_prefix}/current"
    ln -sfT "${tag}" "${snapshot_prefix}/current"
}

# delete tag...
do_delete() {
    local tag
    for tag in "$@"; do
        if [[ -e "${snapshot_prefix}/${tag}" ]]; then
            btrfs subvol delete "${snapshot_prefix}/${tag}" || err "delete volume ${tag} failed, please check ${snapshot_prefix}/${tag}"
        fi
    done
}

# exec [-u user] -t tag cmd...
do_exec() {
    local opt_user=root
    local opt_tag=
    while (($#)); do
        case $1 in
            -u | --user)
                opt_user="$2"
                shift 2
                ;;
            -t | --tag)
                opt_tag="$2"
                shift 2
                ;;
            *)
                break;;
        esac
    done
    [[ -z "${opt_tag}" ]] && die "empty tag"
    [[ ! -e "${snapshot_prefix}/${opt_tag}" ]] && die "exec failed, check tag: ${snapshot_prefix}/${opt_tag}"

    for cmd in "$@"; do
        (cd "${snapshot_prefix}/${opt_tag}" && su "${opt_user}" -c "${cmd}")
    done
}

main() {
    while (( $# )); do
        case $1 in
            -L | --label)
                opt_label="$2"
                shift 2
                ;;
            -p | --prefix)
                opt_prefix="$2"
                shift 2
                ;;
            --subvol)
                opt_subvol="$2"
                shift 2
                ;;
            *)
                break
                ;;
        esac
    done
    defer do_uninit
    do_init

    case "${1}" in
        list)
            shift 1
            do_list "$@"
            ;;
        checkout)
            shift 1
            do_checkout "$@"
            ;;
        delete)
            shift 1
            do_delete "$@"
            ;;
        exec)
            shift 1
            do_exec "$@"
            ;;
        *)
            die "unknown action: $*"
            ;;
    esac
}

main "$@"

