#! /bin/sh

bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.618
bspc config borderless_monocle    false
bspc config gapless_monocle       false

bspc rule -a imv state=floating

