#!/bin/bash
set -e

root_prefix="/"
vols=(root)

die() {
    echo "$@"
    exit 1
}

init() {
    vol_prefix="${root_prefix}mnt/volumes}"
    snapshot_prefix="${root_prefix}mnt/snapshots}"
}

print_usage() {
    cat << EOF
$0 -s [label]               snapshot volume
EOF
}

# snapshot [label]
snapshot() {
    init
    label="$1"
    [[ -z "$label" ]] && label=$(date +%y%m%d%H%M%S)

    for vol in "${vols[@]}"; do
        [[ ! -e "$vol_prefix/$vol" ]] && die "volume $vol does not exist"
    done

    for vol in "${vols[@]}"; do
        btrfs subvol snapshot -r "${snapshot_prefix}/${vol}.latest" "${snapshot_prefix}/${vol}.${label}"
        rm "${snapshot_prefix}/${vol}.latest"
        ln -s "${vol}.${label}" "${snapshot_prefix}/${vol}.latest"
    done
}


while (( $# )); do
case $1 in
    -h | --help)
        print_usage
        exit
        ;;
    -p | --prefix)
        root_prefix="$2"
        shift 2
        ;;
    -s | --snapshot)
        shift
        snapshot "$@"
        exit
        ;;
    *)
        print_usage
        exit 1
        ;;
esac
done
