#!/bin/bash
set -e

vol_prefix="${VOL_PREFIX:-/mnt}"
snapshot_prefix="${SNAPSHOT_PREFIX:-/mnt/@snapshots}"

vols=(@root @home)

die() {
    echo "$@"
    exit 1
}

print_usage() {
    cat << EOF
$0 -s [label]               snapshot volume
$0 -r [label]               rollback snapshot
$0 -d [label]               delete snapshot
EOF
}

# snapshot [label]
snapshot() {
    label="$1"
    [[ -z "$label" ]] && label=$(date +%y%m%d%H%M%S)

    for v in "${vols[@]}"; do
        [[ ! -e "$vol_prefix/$v" ]] && die "volume $v does not exist"
    done
    [[ -e "$snapshot_prefix/$label" ]] && rm -rf "$snapshot_prefix/$label"
    mkdir -p "$snapshot_prefix/$label"
    for v in "${vols[@]}"; do
        btrfs subvol snapshot "$vol_prefix/$v" "$snapshot_prefix/$label/$v"
    done
}

# rollback [label]
rollback() {
    label="$1"
    [[ -z "$label" ]] && label="$(ls "$snapshot_prefix" | sort -n | tail -n 1)"
    [[ -z "$label" ]] && die "undefined label to rollback"

    for v in "${vols[@]}"; do
        [[ ! -e $snapshot_prefix/$label/$v ]] && die "snapshot $label/$v does not exist"
    done

    for v in "${vols[@]}"; do
        [[ -e "$vol_prefix/$v" ]] && (btrfs subvol delete "$vol_prefix/$v" || rm -rf "$vol_prefix/$v")
        btrfs subvol snapshot "$snapshot_prefix/$label/$v" "$vol_prefix/$v"
    done
}

# delete [label]
delete() {
    label="$1"
    [[ -z "$label" ]] && label="$(ls "$snapshot_prefix" | sort -n | tail -n 1)"
    [[ -z "$label" ]] && die "undefined label to rollback"

    for v in "${vols[@]}"; do
        btrfs subvol delete "$snapshot_prefix/$label/$v"
    done
    rm -rf "$snapshot_prefix/$label"
}

case $1 in
    -h | --help)
        print_usage
        exit
        ;;
    -r | --rollback)
        shift
        rollback "$@"
        exit
        ;;
    -s | --snapshot)
        shift
        snapshot "$@"
        exit
        ;;
    -d | --delete)
        shift
        delete "$@"
        exit
        ;;
    *)
        print_usage
        exit 1
        ;;
esac

