#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# xrandr --output HDMI-1 --mode 2560x1440 --rate 144
xsetroot -cursor_name left_ptr

pgrep -x -f /usr/lib/notification-daemon-1.0/notification-daemon || /usr/lib/notification-daemon-1.0/notification-daemon &
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar &
pgrep -x feh > /dev/null || feh --no-fehbg --bg-fill --randomize ~/Pictures/wallpaper/* &
pgrep -x xss-lock > /dev/null || xss-lock -- i3lock -n &

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
pgrep -x fcitx > /dev/null || fcitx -d

exec bspwm

